name: light_joint
recipes: "resources/light/recipes.yaml"
world: 
  name: LightWorld
model: 
  name: ModularACModel
  use_args: true
  max_subtask_timesteps: 100
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/light/hints.indep.yaml"
  max_timesteps: 100
