name: light_joint-feat-plan__3
recipes: "resources/light/recipes.yaml"
world: 
  name: LightWorld
model: 
  name: ModularACModel
  use_args: false
  featurize_plan: true
  max_subtask_timesteps: 15
  baseline: state
  seed: 3
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/light/hints.yaml"
  max_timesteps: 100
