recipes: "resources/recipes.yaml"
world: 
  name: GridWorld
model: 
  name: ModularACModel
  use_args: false
trainer: 
  name: CurriculumTrainer
  improvement_threshold: 0.8
  hints: "resources/hints.simple.yaml"
