name: craft_modular_state-baseline
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACModel
  use_args: false
  max_subtask_timesteps: 15
  baseline: task
trainer: 
  name: CurriculumTrainer
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
