name: craft_holdout
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACModel
  use_args: true
  max_subtask_timesteps: 100
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/craft/hints.holdout.yaml"
  max_timesteps: 100
