name: light_modular
recipes: "resources/light/recipes.yaml"
world: 
  name: LightWorld
model: 
  name: ModularACModel
  use_args: false
  max_subtask_timesteps: 10
  baseline: state
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/light/hints.yaml"
  max_timesteps: 100
