name: craft_modular_state-baseline_longer
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACModel
  use_args: false
  max_subtask_timesteps: 30
  baseline: state
trainer: 
  name: CurriculumTrainer
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
