recipes: "resources/recipes.yaml"
world: 
  name: GridWorld
  #name: LineWorld
model: 
  #name: ReflexModel
  name: ModularACModel
  #name: ModularModel
trainer: 
  name: CurriculumTrainer
  #hints: "resources/hints_indep.yaml"
  hints: "resources/hints.yaml"
