name: light_unsup_unordered__2
recipes: "resources/light/recipes.yaml"
world: 
  name: LightWorld
model: 
  name: ModularACInteractiveModel
  #source: craft_holdout
  use_args: false
  max_subtask_timesteps: 15
  baseline: state
  seed: 2
trainer: 
  name: CurriculumTrainer
  use_curriculum: true
  improvement_threshold: 0.8
  hints: "resources/light/hints.holdout.yaml"
  max_timesteps: 100

#name: craft_transfer
#recipes: "resources/craft/recipes.yaml"
#world: 
#  name: CraftWorld
#model: 
#  name: ModularACModel
#  source: craft_holdout
#  use_args: false
#  max_subtask_timesteps: 15
#  baseline: state
#trainer: 
#  name: CurriculumTrainer
#  use_curriculum: true
#  improvement_threshold: 0.8
#  hints: "resources/craft/hints.holdout.yaml"
#  max_timesteps: 100
