name: craft_modular_common-nostate-baseline_unordered
recipes: "resources/craft/recipes.yaml"
world: 
  name: CraftWorld
model: 
  name: ModularACModel
  use_args: false
  max_subtask_timesteps: 15
  baseline: common
trainer: 
  name: CurriculumTrainer
  improvement_threshold: 0.8
  hints: "resources/craft/hints.yaml"
  max_timesteps: 100
